version: '3.7'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker:/var/lib/postgresql/docker
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
